baseURL: "https://aidan-miranda.github.io/acme/"
languageCode: es-es 
title: Acme Corporation 
theme: basico 
author: 
  facebook: "https://facebook.com/example" 
  twitter: "https://twitter.com/example" 
  email: "contact@example.org" 
  name: "Acme Corporation" 
  location: Zaragoza
  phone: (999) 999-9999 
  hours: "**Lunes-Viernes** 9:00AM - 6:00PM" 

menu:
  main:
    - identifier: about 
      name: Acerca de 
      url: /acerca_de 
      weight: 100 
    - identifier: contact
      name: Contacto 
      url: /contacto 
      weight: 200 
    - identifier: viajes
      name: Viajes
      url: /viajes
      weight: 50  
    - identifier: blog
      name: Blog
      url: /blog
      weight: 40
    - identifier: television
      name: TelevisiÃ³n
      url: /television/television
      weight: 20    
    - identifier: pilares
      name: Pilares
      url: /pilares/pilares
      weight: 10    

params: 
  colorPickerEnabled: true
  color: "#4f46e5"
  copyright: "Copyright &copy; 2022 Acme Corporation. Todos los derechos reservados."
  footer:
  - title: About
    content: >
      Acme Corporation is the world's leading
      manufacturer of digital shapes. From squares and
      circles to triangles and hexagons, we have it
      all. Browse through our collection of various
      forms with different thicknesses and line styles.
      We shape the world. You live in it.      
  - title: Publicaciones recientes
    recents: blog
    recentCount: 7

  - title: Contact Us
    contact: true